### ISSUE TITLE
Okta user cannot be detected when accessing an unprotected route

### ISSUE THREAD

**Issue by kpfefferle** [Hendrick/ring-okta#2]
I need to show/hide certain UI elements on a public route depending on whether the user is logged in via Okta or not. I have exposed the route via `:skip-routes` config, but when an authenticated Okta user accesses the route, `(:okta/user (:session req))` (which usually returns the email of the logged in Okta user) still returns `nil`.

Would it be possible to still have the Okta user email set on the request if a logged in user accesses an unprotected route?

**Comment by bostonaholic** [comment]
@kpfefferle I'm guessing this is when you're using `:force-user`?

**Comment by kpfefferle** [comment]
@bostonaholic Yes, I've been using `:force-user` in Development to test the user being logged in or not.

**Comment by bostonaholic** [comment]
@kpfefferle Good to hear. That's the intended use case!

This has been fixed in `[ring-okta "0.1.5"]`.

Cheers.
